version: "3.4"

services:
  app:
    build: .
    image: app-oak
    restart: "no"
    volumes:
      - .:/app
      - ./app-cache/:/app-cache
    ports:
      - 7777:7777
    depends_on:
      - database
      - flyway
    env_file:
      - ../common/project.env

  database:
    container_name: database-server
    image: postgres:14.1
    restart: "no"
    env_file:
        - ../common/project.env

  flyway:
    image: flyway/flyway:8.4.0-alpine
    depends_on:
      - database
    volumes:
      - ../common:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - ../common/project.env

  k6:
    entrypoint: "/bin/true" # Prevent startup on docker-compose up
    build: ../common/k6
    image: k6
    network_mode: host
    depends_on:
      - app
    volumes:
      - ../common/k6/:/k6/
